### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by kalari123** [NYAN-x-CAT/CSharp-RunPE#1]
So i build it and make program with
 RunPE.Execute(Path.Combine(RuntimeEnvironment.GetRuntimeDirectory(), "RegAsm.exe"), File.ReadAllBytes(""));
and in (""));
i type pastebin link ?

**Comment by NYAN-x-CAT** [comment]
Hi.
You can't use a string link to ReadAllbytes byte[]. I advise you to learn C# before compiling any source in Github.

https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.downloadstring?view=netframework-4.8

https://www.base64code.com/knowledgebase/base64-example-in-csharp/

**Comment by kalari123** [comment]
> Hi.
> You can't use a string link to ReadAllbytes byte[]. I advise you to learn C# before compiling any source in Github.
> 
> https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.downloadstring?view=netframework-4.8
> 
> https://www.base64code.com/knowledgebase/base64-example-in-csharp/

I mean where do i put the runpe i know i convert my file to byte base64 but 
do i put the Rupe.execute(..... in the same project or what
